### ISSUE TITLE
抑制分词时打印的信息

### ISSUE THREAD

**Issue by Freakwill** [fxsjy/jieba#696] opened 2018-12-10 13:30 UTC
分词的时候，会打印下述信息，如何抑制？

> Building prefix dict from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jieba/dict.txt ...
> Loading model from cache /var/folders/md/8kgtqqz12j94hbcvhqz0w7gw0000gp/T/jieba.cache
> Loading model cost 1.2386009693145752 seconds.
> Prefix dict has been built succesfully.

**Comment by lpq29743** [comment] 2018-12-14 12:52
A duplicate of #529

**Closed** 2018-12-15 13:16 UTC
